// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/OrangePortraitEventPoster-8NLM_w/DeepOrangePoster.tsx": () => import("../components/mockups/templates/OrangePortraitEventPoster-8NLM_w/DeepOrangePoster.tsx"),
  "./components/mockups/templates/OrangePortraitEventPoster-B7dzzL/DeepOrangePoster.tsx": () => import("../components/mockups/templates/OrangePortraitEventPoster-B7dzzL/DeepOrangePoster.tsx")
};
